import {it,expect} from '/workspace/ts-pr26-ui-fresh/node_modules/vitest/dist/index.js';
import {periodProfile,localTimes} from '/workspace/ts-pr26-ui-fresh/src/core/period-profile';
const ev=(at:number,song:string,artist:string,ms=180000,exact=true)=>({at,song,name:song,artist,album:null,ms,exact,play:true,earlySkip:false,platform:0,shuffle:false,offline:false,imageUrl:null});
it('calendar 2024 comparison must exclude 31 Dec 2022 while UI says 2023',()=>{const p=periodProfile([ev(Date.UTC(2022,11,31,12),'x','X'),ev(Date.UTC(2023,0,1,12),'y','Y')],{from:Date.UTC(2024,0,1),to:Date.UTC(2025,0,1)},localTimes('UTC'));expect(p.previous?.plays).toBe(1)});
it('displayed most-heard by plays must select the artist with most plays',()=>{const p=periodProfile([ev(1704110400000,'long','Long',1800000,false),...Array.from({length:10},(_,i)=>ev(1704196800000+i*240000,'short'+i,'Frequent',60000,false))],{from:null,to:1800000000000},localTimes('UTC'));expect(p.topArtists[0]?.name).toBe('Frequent')});
it('Lord Howe half-hour daylight saving transition maps actual local day hour',()=>{const at=Date.parse('2024-10-05T15:45:00Z');const actual=localTimes('Australia/Lord_Howe')(at);const fmt=new Intl.DateTimeFormat('en-US',{timeZone:'Australia/Lord_Howe',hour:'numeric',hourCycle:'h23'});expect(actual.hour).toBe(Number(fmt.format(new Date(at))))});
import {writeFileSync} from 'node:fs';
it('writes independently computed browser fixture',()=>{const t=Date.UTC(2024,0,1,12);const p=periodProfile([ev(t,'long','Long',1800000,false),...Array.from({length:10},(_,i)=>ev(t+2400000+i*240000,'short'+i,'Frequent'+ 'Z'.repeat(150),60000,false))],{from:null,to:Date.UTC(2025,0,1)},localTimes('UTC'));writeFileSync('/tmp/final26-ui-fixture.json',JSON.stringify({...p,genres:null,canEstimate:false,genresRetryAt:null,learned:{favorites:1,neverAgain:2,recommendationsKept:3,recommendationsDropped:4,earlySkips:5},coverage:{importedFrom:null,importedTo:null,importedPlays:0,liveSince:t,summaryOnly:false}}))});
it('does not label a known nine-minute gap as without pause',()=>{const t=Date.UTC(2024,0,1,12);const p=periodProfile([ev(t,'one','A',1800000),ev(t+39*60000,'two','A',1800000)],{from:null,to:t+86400000},localTimes('UTC'));writeFileSync('/tmp/final26-ui-session.json',JSON.stringify(p));expect(p.longestSession?.minutes).toBe(30)});
